import type { Metadata } from "next";
import "./globals.css";
import { PrompterProvider } from "../contexts/prompterContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#577BC1]">
        <PrompterProvider>{children}</PrompterProvider>
      </body>
    </html>
  );
}
